name: atime performance tests - run

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Start timer
        run: echo "START_SETUP_TIME=$(date +%s)" >> $GITHUB_ENV
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Safe directory exception
        run: git config --global --add safe.directory '*'
        shell: bash

      - name: Retrieve branch references
        run: |
          git remote add fork "https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git"
          git fetch fork "${GITHUB_HEAD_REF}"
          git switch -c "${GITHUB_HEAD_REF}" "fork/${GITHUB_HEAD_REF}"
          git switch "${GITHUB_BASE_REF}"
          git switch "${GITHUB_HEAD_REF}"
        shell: bash

      - name: R Setup
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Get R library path
        run: |
          echo "R_LIB_PATH=$(Rscript -e 'cat(.libPaths()[1])')" >> $GITHUB_ENV
        shell: bash

      - name: Download R library artifact from main
        uses: dawidd6/action-download-artifact@v10
        with:
          name: r-lib-cache
          path: ${{ env.R_LIB_PATH }}
          if_no_artifact_found: ignore

      - name: Install R packages (DESCRIPTION-specified deps)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: false
          extra-packages: |
            atime
            ggplot2
            directlabels

      - name: Download libgit2 artifact from main
        uses: dawidd6/action-download-artifact@v10
        with:
          name: libgit2-cache
          path: /tmp
          if_no_artifact_found: ignore

      - name: Restore libgit2 from artifact
        run: |
          if [ -f /tmp/libgit2-cache.tar.gz ]; then
            echo "Restoring libgit2 from artifact..."
            sudo tar -xzf /tmp/libgit2-cache.tar.gz -C /
            sudo ldconfig
          fi
        shell: bash

      - name: Install libgit2
        run: |
          if [ ! -f /tmp/libgit2-cache.tar.gz ]; then
            sudo apt-get update -y && sudo apt-get install -y cmake libssl-dev
            git clone --branch v1.6.4 --depth 1 https://github.com/libgit2/libgit2.git
            cd libgit2 && mkdir build && cd build
            cmake .. -DCMAKE_INSTALL_PREFIX=/usr
            make && sudo make install
            cd ../..
            # Create cache tarball with all installed libgit2 files
            echo "Creating libgit2 cache tarball..."
            sudo tar -czf /tmp/libgit2-cache.tar.gz \
              /usr/lib/x86_64-linux-gnu/libgit2* \
              /usr/lib/x86_64-linux-gnu/pkgconfig/libgit2.pc \
              /usr/include/git2* \
              /usr/bin/git2 2>/dev/null || true # Ignore errors if some paths don't exist
            sudo ldconfig # Refresh linker cache
          else
            echo "libgit2 cache tarball already exists, skipping build."
          fi
        shell: bash

      - name: Run atime tests
        run: |
          mkdir -p ~/.R
          echo "CFLAGS = -std=gnu99" >> ~/.R/Makevars
          echo "options(repos = c(CRAN = 'https://cloud.r-project.org'))" >> .Rprofile
          echo "END_SETUP_START_TESTS_TIME=$(date +%s)" >> $GITHUB_ENV
          Rscript -e 'atime::atime_pkg(Sys.getenv("GITHUB_WORKSPACE"), tests.dir = ".ci");'
          echo "END_TESTS_TIME=$(date +%s)" >> $GITHUB_ENV
        shell: bash

      - name: Save timing data
        run: |
          mkdir -p timing
          echo "$START_SETUP_TIME" > timing/start_setup.txt
          echo "$END_SETUP_START_TESTS_TIME" > timing/end_setup.txt
          echo "$END_TESTS_TIME" > timing/end_tests.txt
        shell: bash

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: atime-results
          path: |
            .ci/atime/
            timing/

      - name: Upload PR event
        uses: actions/upload-artifact@v4
        with:
          name: pr-event
          path: ${{ github.event_path }}

      - name: Upload R library artifact
        uses: actions/upload-artifact@v4
        with:
          name: r-lib-cache
          path: ${{ env.R_LIB_PATH }}

      - name: Upload libgit2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: libgit2-cache
          path: /tmp/libgit2-cache.tar.gz
