name: atime performance tests

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    # for testing, to run on empty PRs
    # paths:
    #   - 'R/**'
    #   - 'src/**'
    #   - '.ci/atime/**'
    #   - 'DESCRIPTION'
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Run atime performance analysis
        uses: criticic/r-Autocomment-atime-results@main
        with:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}