name: atime performance tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    # for testing, to run on empty PRs
    # paths:
    #   - 'R/**'
    #   - 'src/**'
    #   - '.ci/atime/**'
    #   - 'DESCRIPTION'

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: criticic/r-Autocomment-atime-results@v1.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}